Models/Domain/BlogPost.cs
namespace portfolio_web_app.Models.Domain
{
    public class BlogPost
    {
        public Guid id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
    }
}

Models/Domain/DevLogPost.cs
namespace portfolio_web_app.Models.Domain
{
    public class DevLogPost
    {
        public Guid id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
    }
}

Models/Domain/Tag.cs
namespace portfolio_web_app.Models.Domain
{
    public class Tag
    {
        public Guid id { get; set; }
        public string Name { get; set; }
        public Guid DevLogID { get;set;}
    }
}

Models/ViewModels/AddBlogPost.cs
namespace portfolio_web_app.Models.ViewModels
{
    public class AddBlogPost
    {
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string PageContent { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
    }
}

Models/ViewModels/AddDevLog.cs
namespace portfolio_web_app.Models.ViewModels
{
    public class AddDevLog
    {
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string PageContent { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
    }
}

Pages/Admin/Blogs/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using portfolio_web_app.Data;
using portfolio_web_app.Models.Domain;

namespace portfolio_web_app.Pages.Admin.Blogs
{
    public class ListModel : PageModel
    {
        private readonly portfolio_web_appContext context;

        public List<BlogPost> blogPosts { get; set; }
        public ListModel(portfolio_web_appContext context)
        {
            this.context = context;
        }

       

        public void OnGet()
        {
            blogPosts = context.BlogPosts.ToList();

        }
    }
}

Pages/Admin/DevLogs/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using portfolio_web_app.Data;
using portfolio_web_app.Models.Domain;
using portfolio_web_app.Models.ViewModels;
using portfolio_web_app.Repositories;

namespace portfolio_web_app.Pages.Admin.DevLogs
{
    public class AddModel : PageModel
    {
        private readonly IDevLogRepository devLogRepository;
        [BindProperty]
        public AddDevLog AddDevLogRequest { get; set; }

        public AddModel(IDevLogRepository devLogRepository) { 
            this.devLogRepository = devLogRepository;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost() {

            var devLogPost = new DevLogPost()
            {
                Heading = AddDevLogRequest.Heading,
                PageTitle = AddDevLogRequest.PageTitle,
                Content = AddDevLogRequest.PageContent,
                ShortDescription = AddDevLogRequest.ShortDescription,
                FeaturedImageUrl = AddDevLogRequest.FeaturedImageUrl,
                PublishedDate = AddDevLogRequest.PublishedDate,
                UrlHandle = AddDevLogRequest.UrlHandle,
                Author = AddDevLogRequest.Author,
                Visible = AddDevLogRequest.Visible
            };

            await devLogRepository.AddAsync(devLogPost);

            return RedirectToPage("/Admin/DevLogs/List");

        }
    }
}

Pages/Admin/DevLogs/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using portfolio_web_app.Data;
using portfolio_web_app.Models.Domain;
using portfolio_web_app.Repositories;

namespace portfolio_web_app.Pages.Admin.DevLogs
{
    public class EditModel : PageModel
    {
        private readonly IDevLogRepository devLogRepository;
		[BindProperty]
        public DevLogPost devLogPost { get; set; }


        public EditModel(IDevLogRepository devLogRepository)
        {
			this.devLogRepository = devLogRepository;
		}

	

		public async Task OnGet(Guid id)
        {
			devLogPost = await devLogRepository.GetAsync(id);

			
        }

		public async Task<IActionResult> OnPostEdit()
		{
            await devLogRepository.UpdateAsync(devLogPost);

            return RedirectToPage("/Admin/DevLogs/List");

        }

        public async Task<IActionResult> OnPostDelete()
        {
            bool deleted = await devLogRepository.DeleteAsync(devLogPost.id);
            if (deleted) {

                return RedirectToPage("/Admin/DevLogs/List");

            }
            return Page();

           
        }
    }
}

Pages/Admin/DevLogs/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using portfolio_web_app.Data;
using portfolio_web_app.Models.Domain;
using portfolio_web_app.Repositories;

namespace portfolio_web_app.Pages.Admin.DevLogs
{
    public class ListModel : PageModel
    {
        private readonly IDevLogRepository devLogRepository;

        public List<DevLogPost> devLogPosts { get; set; }
        public ListModel(IDevLogRepository devLogRepository)
        {
            this.devLogRepository = devLogRepository;
        }

       

        public async Task OnGet()
        {
            //#TODO maybe error here
            devLogPosts = (await devLogRepository.GetAllAsync())?.ToList();

        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace portfolio_web_app.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace portfolio_web_app.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace portfolio_web_app.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/testPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace portfolio_web_app.Pages
{
    public class testPageModel : PageModel
    {
        public void OnGet()
        {
            Console.WriteLine("hello test from dotnet");
        }
    }
}

Pages/Admin/DevLogs/Add.cshtml
@page
@model portfolio_web_app.Pages.Admin.DevLogs.AddModel
@{
}


<div class="bg-secondary bg-opacity-10 py-2 mb-5">

	<div class="container">

		<h1> Add Dev Log </h1>

        
      
	</div>

</div>

<div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="heading" class="form-label">Heading:</label>
                <input type="text" class="form-control" id="heading" asp-for="AddDevLogRequest.Heading">
            </div>
            <div class="mb-3">
                <label for="pageTitle" class="form-label">Page Title:</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="AddDevLogRequest.PageTitle">
            </div>
            <div class="mb-3">
                <label for="pageContent" class="form-label">Content:</label>
                <textarea class="form-control" id="pageContent" asp-for="AddDevLogRequest.PageContent"></textarea>
            </div> 
            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description:</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="AddDevLogRequest.ShortDescription">
            </div>
            <div class="mb-3">
                <label for="featuredImage" class="form-label">Featured Image:</label>
                <input type="text" class="form-control" id="featuredImage" asp-for ="AddDevLogRequest.FeaturedImageUrl">
            </div>
            <div class="mb-3">
                <label for="urlHandle" class="form-label">Url Handle:</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="AddDevLogRequest.UrlHandle">
            </div> 
            <div class="mb-3">
                <label for="publishedDate" class="form-label">Published Date:</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="AddDevLogRequest.PublishedDate">
            </div>
            <div class="mb-3">
                <label for="author" class="form-label">Author:</label>
                <input type="text" class="form-control" id="author" asp-for="AddDevLogRequest.Author">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="isVisible" asp-for="AddDevLogRequest.Visible">
                <label class="form-check-label" for="isVisible">
                    Visible
                </label>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>

Pages/Admin/DevLogs/Edit.cshtml
@page "{id:Guid}"
@model portfolio_web_app.Pages.Admin.DevLogs.EditModel
@{
}


<div class="bg-secondary bg-opacity-10 py-2 mb-5">

	<div class="container">

		<h1> Edit Dev Log </h1>

        
      
	</div>

</div>


@if(Model.devLogPost!=null){
<div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="heading" class="form-label">ID:</label>
                <input type="text" class="form-control" id="id" asp-for="devLogPost.id" readonly>
            </div>
            <div class="mb-3">
                <label for="heading" class="form-label">Heading:</label>
                <input type="text" class="form-control" id="heading" asp-for="devLogPost.Heading">
            </div>
            <div class="mb-3">
                <label for="pageTitle" class="form-label">Page Title:</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="devLogPost.PageTitle">
            </div>
            <div class="mb-3">
                <label for="pageContent" class="form-label">Content:</label>
                <textarea class="form-control" id="pageContent" asp-for="devLogPost.Content"></textarea>
            </div> 
            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description:</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="devLogPost.ShortDescription">
            </div>
            <div class="mb-3">
                <label for="featuredImage" class="form-label">Featured Image:</label>
                <input type="text" class="form-control" id="featuredImage" asp-for="devLogPost.FeaturedImageUrl">
            </div>
            <div class="mb-3">
                <label for="urlHandle" class="form-label">Url Handle:</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="devLogPost.UrlHandle">
            </div> 
            <div class="mb-3">
                <label for="publishedDate" class="form-label">Published Date:</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="devLogPost.PublishedDate">
            </div>
            <div class="mb-3">
                <label for="author" class="form-label">Author:</label>
                <input type="text" class="form-control" id="author" asp-for="devLogPost.Author">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="Visible" asp-for="devLogPost.Visible">
                <label class="form-check-label" for="Visible">
                    Visible
                </label>
            </div>
            <div class="mb-3 d-flex justify-content-between">
                <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>

                <button class="btn btn-danger" type="submit" asp-page-handler="Delete" >Delete</button>
            </div>
        </form>
    </div>
</div>


}else{
    <div class="container">
        <p>Error: dev log not found</p>
    </div>
}

Pages/Admin/DevLogs/List.cshtml
@page
@model portfolio_web_app.Pages.Admin.DevLogs.ListModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">

	<div class="container">

		<h1> Dev Logs </h1>



	</div>

</div>

@if(Model.devLogPosts!=null && Model.devLogPosts.Any()){

	<div class="container">
		<table class="table">
			<thead>
				<tr>
					<td>ID</td>
					<td>Heading</td>
					<td> </td>
				</tr>
			</thead>
			<tbody>
				@foreach(var post in Model.devLogPosts)
				{
					<tr>
						<td>@post.id</td>
						<td>@post.Heading</td>
						<td><a href ="/Admin/DevLogs/Edit/@post.id">View</a></td>
					</tr>
				}
			</tbody>
		</table>

	</div>

}else{

	<div class=" = container">
		<p>Error: No dev logs were found! </p>
	</div>
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Portfolio";
}


<div class="text-center">
    <h1 class="display-4">Sasha Gordon Greene</h1>
    <a class="page-scroll" href="https://google.com" >google</a>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/HuTNV9EbJnY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Portfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/portfolio_web_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Sasha Gordon Greene</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Art</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Mobile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Applications</a>
                        </li>
                        <
                            <li class="nav-item dropdown">
                                <a class= "nav-link dropdown-toggle" href ="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false" id="navbarDropdownAdmin">
                                    Admin
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                    <li>
                                        <a class="dropdown-item" href ="/admin/devLogs/add">Add Dev Log</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="/admin/devLogs/list">View Dev Logs</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="/ArmyBuilder/Builder">Army Builder</a>
                                    </li>

                                </ul>
                                 </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
  
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
   

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Sasha Gordon Greene - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/testPage.cshtml
@page
@model portfolio_web_app.Pages.testPageModel
@{
	ViewData["Title"] = "Portfolio";
}